services:
  gateway:
    image: jkaninda/goma-gateway:latest
    container_name: goma-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS

    volumes:
      # Core configuration
      - ./:/etc/goma

      # Let's Encrypt certificates
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

    networks:
      - web


# -----------------------------
# Networks
# -----------------------------
networks:
  web:
    external: false

# -----------------------------
# Volumes
# -----------------------------
volumes:
  letsencrypt: